baseURL = 'https://ilderajmi.github.io/'
languageCode = 'zh-cn'
title = "I'm Jared Li"

theme = 'paper'

[params]
  color = 'linen'
  avatar = ''
  name = 'Jared Li'
  bio = 'Welcome to my blog'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[taxonomies]
  category = "categories"
  tag = "tags"
